export { getUsuarios } from "./usuarios.js"; // Exporta la función getUsuarios desde el módulo "usuarios.js"
export { getPost } from "./posts.js"; // Exporta la función getPost desde el módulo "posts.js"
export { getCommets } from "./commets.js"; // Exporta la función getCommets desde el módulo "commets.js"
export { getAlbums } from "./albums.js"; // Exporta la función getAlbums desde el módulo "albums.js"
export { getPhotos } from "./photos.js"; // Exporta la función getPhotos desde el módulo "photos.js"
